# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Lagoon' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Lagoon
  pod 'Google/SignIn'
  target 'LagoonTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
